// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDgi-rnivspfyOHRRxaS_x0ReDg-tCcpw',
    appId: '1:290652142552:web:edf5d557aa12feaeae10ad',
    messagingSenderId: '290652142552',
    projectId: 'vending-machine-tycoon',
    authDomain: 'vending-machine-tycoon.firebaseapp.com',
    storageBucket: 'vending-machine-tycoon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkma15X31tpPA_mvRCF8P5sBWSZhU9BHs',
    appId: '1:290652142552:android:bbda446556aa701bae10ad',
    messagingSenderId: '290652142552',
    projectId: 'vending-machine-tycoon',
    storageBucket: 'vending-machine-tycoon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYqBYkBw-stNE4RY2Cm164ahjrPduDzxU',
    appId: '1:290652142552:ios:a2ee3a99ab0d4367ae10ad',
    messagingSenderId: '290652142552',
    projectId: 'vending-machine-tycoon',
    storageBucket: 'vending-machine-tycoon.firebasestorage.app',
    iosBundleId: 'com.example.vendingEmpire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYqBYkBw-stNE4RY2Cm164ahjrPduDzxU',
    appId: '1:290652142552:ios:a2ee3a99ab0d4367ae10ad',
    messagingSenderId: '290652142552',
    projectId: 'vending-machine-tycoon',
    storageBucket: 'vending-machine-tycoon.firebasestorage.app',
    iosBundleId: 'com.example.vendingEmpire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDgi-rnivspfyOHRRxaS_x0ReDg-tCcpw',
    appId: '1:290652142552:web:c23f04fa4f4f87f7ae10ad',
    messagingSenderId: '290652142552',
    projectId: 'vending-machine-tycoon',
    authDomain: 'vending-machine-tycoon.firebaseapp.com',
    storageBucket: 'vending-machine-tycoon.firebasestorage.app',
  );
}
